### ISSUE TITLE
OBS WebSocket exception handling

### ISSUE THREAD

**Issue by aw-was-here** [whatsnowplaying/whats-now-playing#125]
Need to handle the following stack trace better:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/tmp/np/lib/python3.9/site-packages/obswebsocket/core.py", line 226, in run
    message = self.ws.recv()
  File "/tmp/np/lib/python3.9/site-packages/websocket/_core.py", line 354, in recv
    opcode, data = self.recv_data()
  File "/tmp/np/lib/python3.9/site-packages/websocket/_core.py", line 377, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/tmp/np/lib/python3.9/site-packages/websocket/_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
  File "/tmp/np/lib/python3.9/site-packages/websocket/_core.py", line 432, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/tmp/np/lib/python3.9/site-packages/websocket/_abnf.py", line 372, in recv_frame
    self.recv_header()
  File "/tmp/np/lib/python3.9/site-packages/websocket/_abnf.py", line 320, in recv_header
    header = self.recv_strict(2)
  File "/tmp/np/lib/python3.9/site-packages/websocket/_abnf.py", line 407, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/tmp/np/lib/python3.9/site-packages/websocket/_core.py", line 516, in _recv
    return recv(self.sock, bufsize)
  File "/tmp/np/lib/python3.9/site-packages/websocket/_socket.py", line 124, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/np/lib/python3.9/site-packages/obswebsocket/core.py", line 68, in connect
    self.ws.connect("ws://{}:{}".format(self.host, self.port))
  File "/tmp/np/lib/python3.9/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/tmp/np/lib/python3.9/site-packages/websocket/_http.py", line 121, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/tmp/np/lib/python3.9/site-packages/websocket/_http.py", line 201, in _open_socket
    raise err
  File "/tmp/np/lib/python3.9/site-packages/websocket/_http.py", line 176, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/tmp/np/lib/python3.9/site-packages/obswebsocket/core.py", line 245, in run
    self.core.reconnect()
  File "/tmp/np/lib/python3.9/site-packages/obswebsocket/core.py", line 86, in reconnect
    self.connect()
  File "/tmp/np/lib/python3.9/site-packages/obswebsocket/core.py", line 73, in connect
    raise exceptions.ConnectionFailure(str(e))
obswebsocket.exceptions.ConnectionFailure: [Errno 111] Connection refused
```

**Comment by aw-was-here** [comment]
At this point, I believe these are coming from an obswebsocket thread and I don't think there is anyway I can make them go away. :frowning:

**Comment by aw-was-here** [comment]
Won't fix. See above.
