### ISSUE TITLE
json decode failure in twitch token validator

### ISSUE THREAD

**Issue by aw-was-here** [whatsnowplaying/whats-now-playing#980]
```
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nppyi.py", line 14, in <module>
  File "nowplaying\__main__.py", line 86, in main
  File "nowplaying\__main__.py", line 73, in actualmain
  File "nowplaying\systemtray.py", line 44, in __init__
  File "nowplaying\settingsui.py", line 56, in __init__
  File "nowplaying\settingsui.py", line 129, in load_qtui
  File "nowplaying\twitch\settings.py", line 34, in load
  File "nowplaying\twitch\settings.py", line 86, in update_token_name
  File "nowplaying\twitch\utils.py", line 48, in qtsafe_validate_token
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aw-was-here** [comment]
Fixed in 4.2.0 RC1
